default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['-django']
      - id: check-json
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade
        types: [ python ]
        language: system
        args: [--py310-plus]
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [ python ]
        language: system
      - id: flake8
        name: flake8
        entry: poetry run flake8
        types: [ python ]
        language: system
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system
