"""
Revision ID: 7af429110927
Revises: 4070bec716bf
Create Date: 2023-01-07 11:12:10.120393

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7af429110927"
down_revision = "4070bec716bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sweepcast", "id", existing_type=mysql.INTEGER(), type_=sa.String(length=100), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sweepcast", "id", existing_type=sa.String(length=100), type_=mysql.INTEGER(), existing_nullable=False
    )
    # ### end Alembic commands ###
