"""Split columns. Add new columns: volume, open_interest, count, price

Revision ID: 4070bec716bf
Revises: 3912a5f2c4e8
Create Date: 2023-01-07 11:09:07.465626

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4070bec716bf"
down_revision = "3912a5f2c4e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sweepcast", sa.Column("volume", sa.Integer(), nullable=True))
    op.add_column("sweepcast", sa.Column("open_interest", sa.Integer(), nullable=True))
    op.add_column("sweepcast", sa.Column("count", sa.Integer(), nullable=True))
    op.add_column("sweepcast", sa.Column("price", sa.Float(), nullable=True))
    op.drop_column("sweepcast", "vol_oi_ratio")
    op.drop_column("sweepcast", "details")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sweepcast", sa.Column("details", mysql.VARCHAR(length=200), nullable=True))
    op.add_column("sweepcast", sa.Column("vol_oi_ratio", mysql.VARCHAR(length=200), nullable=True))
    op.drop_column("sweepcast", "price")
    op.drop_column("sweepcast", "count")
    op.drop_column("sweepcast", "open_interest")
    op.drop_column("sweepcast", "volume")
    # ### end Alembic commands ###
