"""Add table Option

Revision ID: 295e54b66e6d
Revises: 7af429110927
Create Date: 2023-05-13 14:51:51.378852

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "295e54b66e6d"
down_revision = "7af429110927"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("expiration", sa.Date(), nullable=True),
        sa.Column("strike_price", sa.Float(), nullable=True),
        sa.Column("put_or_call", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("option")
    # ### end Alembic commands ###
