name: CI

on: [push, pull_request]

env:
  TELEGRAM_TOKEN: 0123456789:abcdefghijklmnopqrstuvwxyzabcdefghi
  WEBHOOK_HOST: https://example.host.com
  WEBAPP_HOST: 255.254.253.252
  WEBAPP_PORT: 1234

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/automatic-requirements-txt-for-python-projects
      - uses: actions/checkout@master
      - name: Generate requirements.txt
        id: selftest
        uses: ryan-rozario/pipreqs-action-cpy@master
        with:
          PROJECT_PATH: trade_telegram_bot/
          REQUIREMENT_PATH: requirements.txt

      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install

      - name: Run style checks
        run: make check-codestyle

      - name: Run safety checks
        run: make check-safety

      - name: Run tests
        run: make test
