name: prod

on:
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: 0123456789:abcdefghijklmnopqrstuvwxyzabcdefghi
  WEBHOOK_HOST: https://example.host.com
  WEBAPP_HOST: 255.254.253.252
  WEBAPP_PORT: 1234
  DB_HOST: "${{ secrets.DB_HOST }}"
  DB_USERNAME: "${{ secrets.DB_USERNAME }}"
  DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
  DB_NAME: "${{ secrets.DB_NAME }}"
  REDIS_HOST: example.host.com
  REDIS_PORT: 1234
  REDIS_PASSWORD: password

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/automatic-requirements-txt-for-python-projects
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install

      - name: Apply migrations
        run: make migrate
